language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: JjyE1E+adlM+CitIVpwb9HewJDjY3ZVjDgu8eYcTY+wXRNAvpcNH3gtUUClisXLZ3X4Kd8f875XH7/vUuOtJqMvQDQfUWPbCinE5GDzoRl2S5ZHoRA0H584bqilO7CXjjGMfTBlbw8A5auZ6Vf+n4zTZxgJNvDtple6WRoz/hzg=
  - secure: WcCL4StO7AWOit9MIi0Z7jBnd7axCq2M18FW3kdt/N/D1+AoYGq9vguknhJyQomzsmfpcKY4v10XiGOCX2Wh6YvEaD5TXK59baCPqu8xD4T7MHQLddIdjU95+Y8LYWSD1ARzJL6uwMQW77/GKZJCoRxxr8fgs/LmjUWpkPdgbBQ=
  - secure: ImKGKP+KwPffBBteqP0NnAan94xL1psVFCZo9XdstJ6X/0ykT9GOR39BX5wP4WXC7Z0L6qhh7nRw4MaL82ll7otPz0/7Oi0C3ZUbYR812IsHJO7JxUdgdTnBIFyn7RJ6d3qx99mgPmZ9dFCMnJy7ivjJfvV3BR0sHKz4PX47xmg=
  - secure: oGPp8Lt6nI43N5lM0e5cS1IM6fVM2pBQnaQAfLarXHGo2bJtBnfVkgLIAuI/EoTp5gi1HEIsGd2CF9O2KxeTmw9zTWp84UX9Rw0cO5DaVnG+xL0JFpzdMEzTXEhmeNuo+h9ppU3eSH6656w5vuYfHIGC5RRyVuEYRinq2EHwXWo=
